name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    # ubuntu上でLaravelコンテナを起動して各ステップを実行する
    container:
      image: php:8.0-fpm
      
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample_db
        ports:
          - 3306:3306
          
    steps:
      - uses: actions/checkout@v2
        
      - name: Print php version
        run: |
          php -v
          
      - name: Create Laravel Project
        run: |
             php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
             php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
             php composer-setup.php
             php -r "unlink('composer-setup.php');"
             mv composer.phar /usr/local/bin/composer
             which composer
             # composer create-project  --prefer-dist laravel/laravel my-app
             
      - name: Print composer version
        run: |
          composer -V
          
      - name: Laravel Version
        run: cd my-app && php artisan --version
        
      - name: Laravel Settings
        run: |
          cd my-app && cp ../.env.example .env
          cd my-app && cat .env
          cd my-app && php artisan key:generate
          cd my-app && chmod -R 777 storage bootstrap/cache
          
      - name: Composer Install
        run: cd my-app && composer install

      - name: Composer Dump Autoload
        run: cd my-app && composer dump-autoload -q
