name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    container:
      image: lorisleiva/laravel-docker:8.0
      
    services:
      db-dl:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample_db
        ports:
          - 3306:3306
          
    steps:
      - uses: actions/checkout@v2
      - name: Print Go version
        run: |
          php -v
