name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    # ubuntu上でLaravelコンテナを起動して各ステップを実行する
    container:
      image: php:8.0-fpm
      
    services:
      db-dl:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sample_db
        ports:
          - 3306:3306
          
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Installing TeX Live
        run: |
          sudo apt-get update
    
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
        
      - name: Print Go version
        run: |
          php -v
          composer -V
          
      - name: Create Laravel Project
        run: copy --from=composer:latest /usr/bin/composer /usr/bin/composer 
             composer create-project  --prefer-dist laravel/laravel my-app
